---
- name: Create build context directory
  ansible.builtin.file:
    path: "{{ discogs_api_client_data_path }}/src"
    state: directory
    mode: '0755'
  become: yes
  tags: discogs-api-client

- name: Copy sources to build context
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../../sources"
    dest: "{{ discogs_api_client_data_path }}/src/"
    mode: '0644'
  become: yes
  tags: discogs-api-client

- name: Copy Dockerfile to build context
  ansible.builtin.copy:
    src: Dockerfile
    dest: "{{ discogs_api_client_data_path }}/src/Dockerfile"
    mode: '0644'
  become: yes
  tags: discogs-api-client

- name: Build discogs-api-client Docker image
  community.docker.docker_image:
    name: "{{ discogs_api_client_container_name }}"
    tag: local
    source: build
    build:
      path: "{{ discogs_api_client_data_path }}/src"
      pull: yes
    force_source: yes
  become: yes
  tags: discogs-api-client

- name: Run discogs-api-client container
  community.docker.docker_container:
    name: "{{ discogs_api_client_container_name }}"
    recreate: "{{ docker_force_recreate | default(false) }}"
    image: "{{ discogs_api_client_container_name }}:local"
    restart_policy: always
    state: started
    networks:
      - name: "{{ docker_network }}"
    env:
      DISCOGS_CONSUMER_KEY: "{{ discogs_api_client_consumer_key }}"
      DISCOGS_CONSUMER_SECRET: "{{ discogs_api_client_consumer_secret }}"
      DISCOGS_BASE_URL: "{{ discogs_api_client_base_url }}"
      DISCOGS_SECRET_KEY: "{{ discogs_api_client_secret_key }}"
      DISCOGS_REDIS_URL: "{{ discogs_api_client_redis_url }}"
    labels:
      monitoring.critical: "true"
    log_driver: journald
  become: yes
  no_log: true
  tags: discogs-api-client

- name: Deploy nginx upstream config
  ansible.builtin.template:
    src: nginx-upstream.conf.j2
    dest: "{{ nginx_custom_upstream_path }}/discogs-api-client.conf"
    mode: '0644'
  become: yes
  notify: Reload nginx
  tags: discogs-api-client

- name: Deploy nginx location config
  ansible.builtin.template:
    src: nginx-location.conf.j2
    dest: "{{ discogs_api_client_nginx_custom_locations_path }}/discogs-api-client.conf"
    mode: '0644'
  become: yes
  notify: Reload nginx
  tags: discogs-api-client
...
